### ISSUE TITLE
"Whoops, looks like something went wrong." message, logs included.

### ISSUE THREAD

**Issue by BluePotato5002** [ftbastler/BoNeMEAL#105] opened 2019-08-10 09:05 UTC
**Describe the bug**
I am new to web development and i dont know anything, so what happens with me is that when i try navigating to bonemeal, it shows me the message "Whoops, looks like something went wrong." twice on the same screen, so theyre under each other, and i cant install because when i go to localhost/bonemeal/index.php/install, the same error appears, logs below
**Expected behavior**
It should have directed me to the installation wizard or atleast the website itself

**Screenshots**
![image](https://user-images.githubusercontent.com/37984558/62820028-a4f3a500-bb66-11e9-8fb2-7c59021d7926.png)

**Server Environment (please complete the following information):**
 - OS: [Windows]
 - PHP Version: PHP 7.1.30

** Log Files **
https://paste.ubuntu.com/p/GSG8SRkj5h/

**Additional context**
I tried both XAMPP and standalone apache and it gave the same results

**Comment by oranges13** [comment] 2019-08-10 14:34
Hey there! Thank you for your thorough bug report, this is very helpful.

So your log file says the issue is `ErrorException: Function mcrypt_get_iv_size() is deprecated ` this application is written in an older version of Laravel that doesn't really support PHP 7.1 very well.

If you have the option to do so, can you try downgrading to 5.6 and seeing if that works for you?

If not, I have outlined procedures to attempt to modify some files to get it working with 7.1 in this other issue: https://github.com/ftbastler/BoNeMEAL/issues/87#issuecomment-511229130

Let me know if these options work for you. Otherwise, I am in the process of upgrading this application so that it will function with newer versions of PHP.

**Comment by oranges13** [comment] 2019-11-05 21:35
This should be fixed with the newest release, which now supports PHP versions 7+

**Closed as completed by oranges13** 2019-11-05 21:35 UTC
